### ISSUE TITLE
VNCLog Not working

### ISSUE THREAD

**Issue by sathiyaraj-github** [sibson/vncdotool#208] opened 2022-01-13 05:48 UTC
Have you included the following information?

 - [Enabled Dell IDRAC9 ] VNC server and version
 - [0.12.0 ] vncdotool version
 - [ enable vnc in dell idrac console, then install vncviewer and vncdotool in the localhost, then run the command as per the document to capture the log] steps to reproduce
 - FYI: https://vncdotool.readthedocs.io/_/downloads/en/v0.9.0/pdf/

**Comment by pmhahn** [comment] 2022-12-20 09:57
Probably a duplicate of issue #140

**Closed** 2022-12-23 13:53 UTC

**Comment by pmhahn** [comment] 2022-12-27 08:06
I only checked `vnclog` briefly and I had hoped that https://github.com/univention/vncdotool/commit/a72210eddd5495bbf90d7ae450a4c2e995b9393c fixed the bug, but in my short test it did not.
