### ISSUE TITLE
Capturing screen twice in script

### ISSUE THREAD

**Issue by brumer** [sibson/vncdotool#70] opened 2016-09-04 10:17 UTC
Hi, im using vncdo as a command line tool with a script.
In the script there are a couple of "capture" commands.
It seems the second one always hangs and the tool is stuck
what can i do?

**Comment by HeavyThumper** [comment] 2016-09-06 00:01
Offhand, if one command works and another doesn't - I'd say the problem is 
with your command. You didn't share those so it's difficult to comment further.

Daniel

**Comment by sibson** [comment] 2017-02-10 05:15
I've made some improvements to screen capturing. Could you let me know if you are having issues still.  If so please include the script you are running and the VNC server you are working with.

**Comment by gottsman** [comment] 2017-11-15 17:11
My simple script hangs while capturing screenshots. Is it possible to add a timeout argument or automatically kill the user request after xxx seconds? In the past, I've run the "gtimeout" to stop the hanging.

Multiple vncdo versions (primarily 0.10.0 and master)
VMLite VNC Server (https://play.google.com/store/apps/details?id=com.vmlite.vncserver&hl=en)

```
    for i in 1 2 3 4 5; do
        echo "Capturing device $i..."
        vncdotool -s 192.168.3.$i::5901 capture 192.168.3.$i.png
    done
```

**Comment by sibson** [comment] 2017-11-15 20:27
@gottsman Is [--timeout](https://github.com/sibson/vncdotool/blob/master/vncdotool/command.py#L383-L384) not working properly? If not that sounds like a new issue.

**Comment by gottsman** [comment] 2017-11-15 21:41
Didn't know the option was available.... Will have to try it out.

My primary method of using vncdotool is through the API. Is there a similar option available? One wasn't identified in the documentation I found. If there is, can you provide a very simple example?

http://vncdotool.readthedocs.io/en/latest/

**Comment by sibson** [comment] 2017-11-16 00:56
I don't think there is an easy way to set a timeout via the API.  I think we'd need to find a way to make [this timeout](https://github.com/sibson/vncdotool/blob/7dfdbb492a4193a1f904ecaecb2acdc1d176d0eb/vncdotool/api.py#L109) configurable, either globally or on a per call basis.  It's probably easier to start with a class level global option.  At this point I think we've diverged enough from the original issue that we should continue discussion on a new ticket.

**Comment by pmhahn** [comment] 2023-02-04 11:31
ada0e7ad703aabdc1b07f58f0c9755d6589cf564 added the ability to control the `--incremental` flag, which must be set to `False` when you want to do multiple `capture`s from the same process. Otherwise `vncdotool` will get stuck if the screen is unchanged, as the server will then send no _update rectangles_ and the client has no chance to detect, that it can proceed.

As version `0.10.0` and this issue is many years old, I'll close this issue as `vncdo capture` works for me.

**Closed by pmhahn** 2023-02-04 11:31 UTC
