### ISSUE TITLE
vncdotool capture screen bug

### ISSUE THREAD

**Issue by jiangtaixing** [sibson/vncdotool#191] opened 2021-07-16 05:56 UTC
vncdotool cannot work without vnc client when capture the screen

**Comment by Kochise** [comment] 2021-11-02 10:25
Seems logical...

**Comment by genestealer** [comment] 2022-03-01 14:48
Suggest to close this

**Closed** 2022-12-11 15:12 UTC

**Comment by sibson** [comment] 2022-12-11 15:13
unclear what the issue is
